exports.rebus = {
	"a walk in the park": "http://i.imgur.com/HmpdxJa.gif",
	"tuna fish": "http://i.imgur.com/yeTQDzZ.jpg",
	"point blank range": "http://i.imgur.com/hqTCgHB.gif",
	"dominoe": "http://i.imgur.com/KcuMMUK.gif",
	"down to earth": "http://i.imgur.com/A1b1LPP.jpg",
	"total loss": "http://i.imgur.com/HmnWHgm.gif",
	"three blind mice": "http://i.imgur.com/IE4SqzO.gif",
	"line up in alphabetical order": "http://i.imgur.com/9zDPvqK.gif",
	"sitting on top of the world": "http://i.imgur.com/chUoAIi.gif",
	"shifting gears": "http://i.imgur.com/1bjmXbV.gif",
	"contract extension": "http://i.imgur.com/cN56jEj.gif",
	"you deserve a break today": "http://i.imgur.com/Zby1BOO.gif",
	"break the bank": "http://i.imgur.com/6ar6zIv.gif",
	"crossfire": "http://i.imgur.com/oeOwD87.gif",
	"horsing around": "http://i.imgur.com/bBvPA1x.gif",
	"tennis shoe": "http://i.imgur.com/eL5syJM.gif",
	"blanket": "http://i.imgur.com/n84zKob.gif",
	"take from the rich give to the poor": "http://i.imgur.com/2nuW13I.gif",
	"repeat after me": "http://i.imgur.com/ilIPN1j.gif",
	"crossing guard": "http://i.imgur.com/zKmjY3C.gif",
	"double time": "http://i.imgur.com/bbsqOZb.gif",
	"right beside me": "http://i.imgur.com/Npppq4z.gif",
	"rail crossing": "http://i.imgur.com/EguH7sJ.gif",
	"breaking a custom": "http://i.imgur.com/2PhIXre.gif",
	"platinum": "http://i.imgur.com/4WBrOix.gif",
	"foreign language": "http://i.imgur.com/qShcVhj.gif",
	"who's in-charge": "http://i.imgur.com/DNKjjqt.gif",
	"highway overpass": "http://i.imgur.com/p6Zq9oe.gif",
	"search high and low": "http://i.imgur.com/YKOKmFM.gif",
	"hitting below the belt": "http://i.imgur.com/ifod7Rs.gif",
	"easy on the eyes": "http://i.imgur.com/MCSjFWo.gif",
	"too big to ignore": "http://i.imgur.com/EcXbFhs.gif",
	"play in the yard": "http://i.imgur.com/vxQhT6p.gif",
	"excuse me": "http://i.imgur.com/07O7Sko.gif",
	"painless operation": "http://i.imgur.com/w0ZQeSu.gif",
	"i'll be there in a minute": "http://i.imgur.com/vHkr6g6.gif",
	"an after thought": "http://i.imgur.com/YBisOVv.gif",
	"life after death": "http://i.imgur.com/DyKhNUs.gif",
	"crossbow": "http://i.imgur.com/O3ZUY6Y.gif",
	"frankenstein": "http://i.imgur.com/GeYZ2fd.gif",
	"ring around the rose": "http://i.imgur.com/16cL2j6.gif",
	"four wheel drive": "http://i.imgur.com/6hDwR5V.gif",
	"two in one": "http://i.imgur.com/il2V3da.gif",
	"tiptoe through the tulips": "http://i.imgur.com/kBTorba.gif",
	"safety in numbers": "http://i.imgur.com/WXhIPn9.gif",
	"just in case": "http://i.imgur.com/bcXoFLJ.gif",
	"once upon a time": "http://i.imgur.com/BGAbDaM.gif",
	"three strikes you're out": "http://i.imgur.com/ypZ0hzv.gif",
	"big time operator": "http://i.imgur.com/qUOalD9.gif",
	"day in day out": "http://i.imgur.com/1RZAVjr.gif",
	"ill in bed": "http://i.imgur.com/VULufKa.gif",
	"two-faced": "http://i.imgur.com/ca4hvr6.gif",
	"square dance": "http://i.imgur.com/FUGF89u.gif",
	"order in the court": "http://i.imgur.com/5Q9xsol.gif",
	"mirror image": "http://i.imgur.com/Nq4Ugon.gif",
	"up for grabs": "http://i.imgur.com/PqUU8Tf.gif",
	"circles under the eyes": "http://i.imgur.com/9vIOiKT.gif",
	"water": "http://i.imgur.com/zTJTaXh.gif",
	"you win some you lose some": "http://i.imgur.com/0KAB6H8.gif",
	"a pair of pants": "http://i.imgur.com/h0h4pJF.gif",
	"higher learning": "http://i.imgur.com/F20O6Vz.gif",
	"inside out": "http://i.imgur.com/0vlVSDO.gif",
	"lowest power": "http://i.imgur.com/RAqDc5W.gif",
	"count on us": "http://i.imgur.com/dqaMMQF.gif",
	"strawberry shortcake": "http://i.imgur.com/iSXjZzh.gif",
	"tuesday": "http://i.imgur.com/gCZgRkn.gif",
	"green with envy": "http://i.imgur.com/wqWZvSf.gif",
	"without a second glance": "http://i.imgur.com/FFDUFgu.gif",
	"no doubt about it": "http://i.imgur.com/Qy7vjP8.gif",
	"multiple choice": "http://i.imgur.com/7A4b4Fv.gif",
	"backseat driver": "http://i.imgur.com/IwVLVJa.gif",
	"middle of the night": "http://i.imgur.com/3PVVtsH.gif",
	"partly cloudy": "http://i.imgur.com/uoRi6lG.gif",
	"vitamin A defeciency": "http://i.imgur.com/SKbnvEq.gif",
	"quit following me": "http://i.imgur.com/uyXPojA.gif",
	"waterfall": "http://i.imgur.com/EX5oQ4a.gif",
	"illegal": "http://i.imgur.com/Ae5smeC.gif",
	"long underwear": "http://i.imgur.com/2zFs8KT.gif",
	"a hole in one": "http://i.imgur.com/iLSkxQc.gif",
	"a house divided": "http://i.imgur.com/DG0d2nC.gif",
	"ambiguous": "http://i.imgur.com/zVzbaZP.gif",
	"sleeping on the job": "http://i.imgur.com/reedDwR.gif",
	"water under the bridge": "http://i.imgur.com/V6yloCo.gif",
	"suspended animation": "http://i.imgur.com/8baz9JT.gif",
	"getting up at the break of dawn": "http://i.imgur.com/ZpAYtQU.gif",
	"space program": "http://i.imgur.com/yiMSdAa.gif",
	"no left turn": "http://i.imgur.com/1fR61km.gif",
	"he's beside himself": "http://i.imgur.com/hR6BXXF.gif",
	"three degrees below zero": "http://i.imgur.com/Ho7TE1O.gif",
	"i understand": "http://i.imgur.com/O11udmq.gif",
	"sandbox": "http://i.imgur.com/gUY5bot.gif",
	"stand in the corner": "http://i.imgur.com/RtjIpZd.gif",
	"bend over backwards": "http://i.imgur.com/icyfR7B.gif",
	"all hands on deck": "http://i.imgur.com/hFsJKZH.gif",
	"long goodbye": "http://i.imgur.com/qDrNfjA.gif",
	"kung fu panda": "http://i.imgur.com/3dfWDgD.jpg",
	"inbox": "http://i.imgur.com/e9ZSjAm.gif",
	"diamond ring": "http://i.imgur.com/vwedzuH.gif",
	"white elephant": "http://i.imgur.com/yWGfaME.jpg",
	"art": "http://i.imgur.com/jHKesRL.gif",
	"northern hemisphere": "http://i.imgur.com/mBY0ci2.gif",
	"all over again": "http://i.imgur.com/FGAEtT3.gif",
	"all over the houses": "http://i.imgur.com/YIflg2b.gif",
	"first aide": "http://i.imgur.com/QE266jn.jpg",
	"top secret": "http://i.imgur.com/rz4FD9i.jpg",
	"free beer for a year": "http://i.imgur.com/GQaiwuL.jpg",
	"horse back riding": "http://i.imgur.com/LV7QZmb.jpg",
	"bear": "http://i.imgur.com/UBHRgsv.jpg",
	"somewhere over the rainbow": "http://i.imgur.com/1XHYfE8.jpg",
	"nowhere in sight": "http://i.imgur.com/1evDvn5.gif",
	"mixed doubles": "http://i.imgur.com/EysWV0y.gif",
	"outside chance": "http://i.imgur.com/dLQZVfc.gif",
	"the beginning of the end": "http://i.imgur.com/4za8sTp.gif",
	"full time part time": "http://i.imgur.com/X42Beng.gif",
	"a cut above the rest": "http://i.imgur.com/vG5APFJ.gif",
	"working overtime": "http://i.imgur.com/h6HIaw0.gif",
	"two in one": "http://i.imgur.com/7AO5eIE.gif",
	"lemonade": "http://i.imgur.com/Wf7IVrd.gif",
	"go long": "http://i.imgur.com/8Y40uil.gif",
	"tall tale": "http://i.imgur.com/CntTe5F.gif",
	"touchdown": "http://i.imgur.com/IISCMDY.gif",
	"a man for all seasons": "http://i.imgur.com/aKB2bLT.gif",
	"a round of applause": "http://i.imgur.com/JcQXKYt.gif",
	"a step backwards": "http://i.imgur.com/Vx7uS39.gif",
	"alice in wonderland": "http://i.imgur.com/NZpLvrP.gif",
	"bad influence": "http://i.imgur.com/o5bKzEN.gif",
	"balanced budget": "http://i.imgur.com/KGcq8eT.gif",
	"banana split": "http://i.imgur.com/T9g1ihO.gif",
	"better safe than sorry": "http://i.imgur.com/KUZmyjX.gif",
	"big bird": "http://i.imgur.com/WSgD6iu.gif",
	"big foot": "http://i.imgur.com/8CpuHXA.gif",
	"big man on campus": "http://i.imgur.com/WEvn7dj.gif",
	"black over coat": "http://i.imgur.com/Q3Z9G7f.gif",
	"blood is thicker than water": "http://i.imgur.com/sWizrvZ.gif",
	"broken nose": "http://i.imgur.com/Ny9PC1z.gif",
	"camping overnight": "http://i.imgur.com/kA58mBA.gif",
	"captain hook": "http://i.imgur.com/HIKWthM.gif",
	"coffee break": "http://i.imgur.com/bn8NMfF.gif",
	"crossroads": "http://i.imgur.com/jdE7BWQ.gif",
	"diamond in the rough": "http://i.imgur.com/RJFtLhL.gif",
	"double agent": "http://i.imgur.com/wSCVfuN.gif",
	"downpour": "http://i.imgur.com/F6OmvWM.gif",
	"downtown": "http://i.imgur.com/NfsNVuk.gif",
	"eavesdropping": "http://i.imgur.com/K982Aif.gif",
	"elevator out of order": "http://i.imgur.com/x1CZnn5.gif",
	"end of time": "http://i.imgur.com/8zXkXci.gif",
	"equal rights": "http://i.imgur.com/vgEnOru.gif",
	"extended family": "http://i.imgur.com/ziviZPw.gif",
	"eye chart": "http://i.imgur.com/pGYy8Eu.gif",
	"falling in love": "http://i.imgur.com/vKpWB7W.gif",
	"falling star": "http://i.imgur.com/pg1y7wc.gif",
	"forgive and forget": "http://i.imgur.com/Fk1WOOA.gif",
	"forgive and forget": "http://i.imgur.com/5yU6yhw.gif",
	"generation gap": "http://i.imgur.com/DuJCsZd.gif",
	"go for it": "http://i.imgur.com/6jXOrPr.gif",
	"good intentions": "http://i.imgur.com/93zZp18.gif",
	"growing economy": "http://i.imgur.com/DuF2rdy.gif",
	"growing old": "http://i.imgur.com/roP8KaF.gif",
	"water": "http://i.imgur.com/FnSN3ON.gif",
	"half-hearted": "http://i.imgur.com/Dfx3u26.gif",
	"half time": "http://i.imgur.com/fjPtrZD.gif",
	"head for cover": "http://i.imgur.com/z4iJ6sX.gif",
	"head in the sand": "http://i.imgur.com/M0mAOtD.gif",
	"head over heels in love": "http://i.imgur.com/oxkQIif.gif",
	"head over heels": "http://i.imgur.com/YFhpzyZ.gif",
	"high chair": "http://i.imgur.com/MCiJl9Q.gif",
	"ice cube": "http://i.imgur.com/dMrcVyX.gif",
	"i'll get over it": "http://i.imgur.com/3T57KED.gif",
	"i'm bigger than you": "http://i.imgur.com/7JXxAFd.gif",
	"in between jobs": "http://i.imgur.com/vkelilO.gif",
	"jack in a box": "http://i.imgur.com/ROMHICd.gif",
	"history repeats itself": "http://i.imgur.com/6yZMDLP.gif",
	"just between you and me": "http://i.imgur.com/MKQf6wa.gif",
	"life begins at 40": "http://i.imgur.com/bQtycCY.gif",
	"long time no see": "http://i.imgur.com/8kiumnh.gif",
	"look inside": "http://i.imgur.com/qvSCKGt.gif",
	"love at first sight": "http://i.imgur.com/Ay2pGoJ.gif",
	"made in China": "http://i.imgur.com/COmMNE1.gif",
	"make up": "http://i.imgur.com/L35LvWK.gif",
	"man in the moon": "http://i.imgur.com/LfQD6Cg.gif",
	"man overboard": "http://i.imgur.com/tilNcjW.gif",
	"merry go round": "http://i.imgur.com/VORxXLq.gif",
	"microscope": "http://i.imgur.com/0LpmMAv.gif",
	"millionaire": "http://i.imgur.com/f2aKNep.gif",
	"mind over matter": "http://i.imgur.com/8mGAlOx.gif",
	"missing you": "http://i.imgur.com/Q6blrbf.gif",
	"more often than not": "http://i.imgur.com/Uwwy9rG.gif",
	"never ending love": "http://i.imgur.com/yrk6k4p.gif",
	"no one to blame": "http://i.imgur.com/kZmTTKH.gif",
	"no u-turn": "http://i.imgur.com/QfsbEnk.gif",
	"odds are against you": "http://i.imgur.com/UWdV0rK.gif",
	"on cloud nine": "http://i.imgur.com/cXvrsnk.gif",
	"once in a blue moon": "http://i.imgur.com/yEoz6Dn.gif",
	"one in a million": "http://i.imgur.com/lLfSOt3.gif",
	"pen is mightier than sword": "http://i.imgur.com/276PGuP.gif",
	"raised eyebrows": "http://i.imgur.com/4zUrkht.gif",
	"reading between the lines": "http://i.imgur.com/QadgVF3.gif",
	"repeat after me": "http://i.imgur.com/jsfFIhr.gif",
	"sailing the seven seas": "http://i.imgur.com/dktRMEg.gif",
	"scrambled eggs": "http://i.imgur.com/PTphyZo.gif",
	"settle down": "http://i.imgur.com/NHyZr4E.gif",
	"seven eleven": "http://i.imgur.com/2j8jsL0.gif",
	"shape up": "http://i.imgur.com/1WtHDpv.gif",
	"short visit": "http://i.imgur.com/apINyvG.gif",
	"shut up": "http://i.imgur.com/uvmAVib.gif",
	"singing in the rain": "http://i.imgur.com/SBDtUJF.gif",
	"six feet underground": "http://i.imgur.com/DwCq6ga.gif",
	"space invaders": "http://i.imgur.com/KDDwCzB.gif",
	"split level": "http://i.imgur.com/A5TPx4V.gif",
	"stuck up": "http://i.imgur.com/PAvTBAy.gif",
	"thanks a lot": "http://i.imgur.com/18s8kg0.gif",
	"the good the bad and the ugly": "http://i.imgur.com/F6m986J.gif",
	"too sweet to be forgotten": "http://i.imgur.com/mAOmUPw.gif",
	"tricycle": "http://i.imgur.com/6P2eyuz.gif",
	"tripod": "http://i.imgur.com/OsIA8CE.gif",
	"try to understand": "http://i.imgur.com/sPFfN7P.gif",
	"two peas in a pod": "http://i.imgur.com/IAp7qGZ.gif",
	"undercover": "http://i.imgur.com/L0ZIrkM.gif",
	"unfinished business": "http://i.imgur.com/RmBcFdU.gif",
	"unfinished symphony": "http://i.imgur.com/RYGzo58.gif",
	"update": "http://i.imgur.com/0KhLPYT.gif",
	"win with ease": "http://i.imgur.com/vPTDHKw.gif",
	"world without end": "http://i.imgur.com/IHWtiBs.gif",
	"you're under arrest": "http://i.imgur.com/4w8PguR.gif",
};