exports.twistables = [
	{
		categ: "American States",
		list: [
			"Alabama",
			"Hawaii",
			"Massachusetts",
			"New Mexico",
			"South Dakota",
			"Alaska",
			"Idaho",
			"Michigan",
			"New York",
			"Tennessee",
			"Arizona",
			"Illinois",
			"Minnesota",
			"North Carolina",
			"Texas",
			"Arkansas",
			"Indiana",
			"Mississippi",
			"North Dakota",
			"Utah",
			"California",
			"Iowa",
			"Missouri",
			"Ohio",
			"Vermont",
			"Colorado",
			"Kansas",
			"Montana",
			"Oklahoma",
			"Virginia",
			"Connecticut",
			"Kentucky",
			"Nebraska",
			"Oregon",
			"Washington",
			"Delaware",
			"Louisiana",
			"Nevada",
			"Pennsylvania",
			"West Virginia",
			"Florida",
			"Maine",
			"New Hampshire",
			"Rhode Island",
			"Wisconsin",
			"Georgia",
			"Maryland",
			"New Jersey",
			"South Carolina",
			"Wyoming",
		]
	},
	{
		categ: "Countries",
		list: [
			"Afghanistan",
			"Albania",
			"Algeria",
			"Andorra",
			"Angola",
			"Antigua and Barbuda",
			"Argentina",
			"Armenia",
			"Aruba",
			"Australia",
			"Austria",
			"Azerbaijan",
			"The Bahamas",
			"Bahrain",
			"Bangladesh",
			"Barbados",
			"Belarus",
			"Belgium",
			"Belize",
			"Benin",
			"Bhutan",
			"Bolivia",
			"Bosnia and Herzegovina",
			"Botswana",
			"Brazil",
			"Brunei",
			"Bulgaria",
			"Burkina Faso",
			"Burma",
			"Burundi",
			"Cambodia",
			"Cameroon",
			"Canada",
			"Cape Verde",
			"Central African Republic",
			"Chad",
			"Chile",
			"China",
			"Colombia",
			"Comoros",
			"Democratic Republic of the Congo",
			"Costa Rica",
			"Cote d'Ivoire",
			"Croatia",
			"Cuba",
			"Curacao",
			"Cyprus",
			"Czech Republic",
			"Denmark",
			"Djibouti",
			"Dominica",
			"Dominican Republic",
			"East Timor",
			"Ecuador",
			"Egypt",
			"El Salvador",
			"Equatorial Guinea",
			"Eritrea",
			"Estonia",
			"Ethiopia",
			"Fiji",
			"Finland",
			"France",
			"Gabon",
			"The Gambia",
			"Georgia",
			"Germany",
			"Ghana",
			"Greece",
			"Grenada",
			"Guatemala",
			"Guinea",
			"Guinea-Bissau",
			"Guyana",
			"Haiti",
			"Holy See",
			"Honduras",
			"Hong Kong",
			"Hungary",
			"Iceland",
			"India",
			"Indonesia",
			"Iran",
			"Iraq",
			"Ireland",
			"Israel",
			"Italy",
			"Jamaica",
			"Japan",
			"Jordan",
			"Kazakhstan",
			"Kenya",
			"Kiribati",
			"North Korea",
			"South Korea",
			"Kosovo",
			"Kuwait",
			"Kyrgyzstan",
			"Laos",
			"Latvia",
			"Lebanon",
			"Lesotho",
			"Liberia",
			"Libya",
			"Liechtenstein",
			"Lithuania",
			"Luxembourg",
			"Macau",
			"Macedonia",
			"Madagascar",
			"Malawi",
			"Malaysia",
			"Maldives",
			"Mali",
			"Malta",
			"Marshall Islands",
			"Mauritania",
			"Mauritius",
			"Mexico",
			"Micronesia",
			"Moldova",
			"Monaco",
			"Mongolia",
			"Montenegro",
			"Morocco",
			"Mozambique",
			"Namibia",
			"Nauru",
			"Nepal",
			"Netherlands",
			"Netherlands Antilles",
			"New Zealand",
			"Nicaragua",
			"Niger",
			"Nigeria",
			"North Korea",
			"Norway",
			"Oman",
			"Pakistan",
			"Palau",
			"Palestinian Territories",
			"Panama",
			"Papua New Guinea",
			"Paraguay",
			"Peru",
			"Philippines",
			"Poland",
			"Portugal",
			"Qatar",
			"Romania",
			"Russia",
			"Rwanda",
			"Saint Kitts and Nevis",
			"Saint Lucia",
			"Saint Vincent and the Grenadines",
			"Samoa",
			"San Marino",
			"Sao Tome and Principe",
			"Saudi Arabia",
			"Senegal",
			"Serbia",
			"Seychelles",
			"Sierra Leone",
			"Singapore",
			"Sint Maarten",
			"Slovakia",
			"Slovenia",
			"Solomon Islands",
			"Somalia",
			"South Africa",
			"South Korea",
			"South Sudan",
			"Spain ",
			"Sri Lanka",
			"Sudan",
			"Suriname",
			"Swaziland",
			"Sweden",
			"Switzerland",
			"Syria",
			"Taiwan",
			"Tajikistan",
			"Tanzania",
			"Thailand",
			"Timor-Leste",
			"Togo",
			"Tonga",
			"Trinidad and Tobago",
			"Tunisia",
			"Turkey",
			"Turkmenistan",
			"Tuvalu",
			"Uganda",
			"Ukraine",
			"United Arab Emirates",
			"United Kingdom",
			"Uruguay",
			"Uzbekistan",
			"Vanuatu",
			"Venezuela",
			"Vietnam",
			"Yemen",
			"Zambia",
			"Zimbabwe",
		]
	},
	{
		categ: "Moves",
		list: [
			"Absorb",	
			"Acid",
			"Acid Armor",
			"Aerial Ace",
			"Agility",
			"Air Cutter",
			"Amnesia",	  
			"AncientPower",	  
			"Arm Thrust",
			"Aromatherapy",	  
			"Assist",
			"Astonish",
			"Attract",	  
			"Aurora Beam",	
			"Barrier",  
			"Baton Pass",	  
			"Belly Drum",	  
			"Bide",
			"Bind",  
			"Bite",
			"Blaze Kick",	  
			"Blizzard",  
			"Block",
			"Body Slam",	
			"Bounce",  
			"Brick Break",
			"Bubble",
			"BubbleBeam",
			"Bulk Up",
			"Bullet Seed",
			"Calm Mind",
			"Camouflage",	  
			"Charge",  
			"Charm",
			"Clamp",
			"Confuse Ray",	  
			"Confusion",
			"Constrict",
			"Cosmic Power",	  
			"Cotton Spore",
			"Counter",  
			"Covet",
			"CrabHammer",	  
			"Cross Chop",  
			"Crunch",
			"Crush Claw",
			"Curse",
			"Cut",
			"Dark Void",
			"Defense Curl",
			"Destiny Bond",
			"Detect",
			"Dig",
			"Disable",	  
			"Dive",
			"Dizzy Punch",	
			"Double Kick",	  
			"Double Team",	  
			"Double-Edge", 
			"Double Slap",
			"Dragon Claw",
			"Dragon Dance",	  
			"Dragon Rage",
			"DragonBreath",	
			"Dream Eater",
			"Drill Peck",  
			"Dynamicpunch",	
			"Earthquake",
			"Ember",  
			"Encore",		  
			"Endeavor",	  
			"Endure",  
			"Eruption",	  
			"Explosion",
			"Extrasensory",	
			"ExtremeSpeed",
			"Earth Power",	  
			"Façade",	  
			"Faint Attack",	  
			"Fake out",
			"Fake Tears",
			"False Swipe",	
			"Fire Blast",	  
			"Fire Punch",	  
			"Fire Spin",
			"Fissure",		
			"Flail",
			"Flamethrower",
			"Flash",
			"Flatter",  
			"Fly",
			"Focus Energy",
			"Focus Punch",  
			"Foresight",  
			"Frustration",
			"Freeze Dry",
			"Fury Attack",	
			"Fury Cutter",	  
			"Fury Swipes",	
			"Future Sight",  
			"Giga Drain",
			"Glare",
			"Grasswhistle",
			"Growl",
			"Grudge",		  
			"Guillotine",
			"Gust",
			"Hail",
			"Harden",	 	  
			"Haze",
			"Headbutt",
			"Heal Bell",	  
			"Heat Wave",	  
			"Helping Hand",
			"Hi Jump Kick", 
			"Hidden Power",	  
			"Horn Attack",
			"Horn Drill",
			"Howl",  
			"Hydro Pump",	  
			"Hyper Beam",
			"Hyper Voice",
			"Hypnosis",
			"Ice Ball",		  
			"Ice Beam",	
			"Ice Punch",	  
			"Icy Wind",	
			"Imprison",	  
			"Ingrain",	  
			"Iron Defense",	  
			"Iron Tail",
			"Karate Chop",	  
			"Kinesis",	  
			"Knock Off",	
			"Leaf Blade",	  
			"Leech Life",	
			"Leech Seed",	
			"Leer",
			"Lick",
			"Light Screen",	  
			"Lock on",
			"Low Kick",
			"Luster Purge",
			"Mach Punch",	  
			"Magic Coat",  
			"Magic Leaf",	  
			"Magnitude",
			"Mean Look",
			"Meditate",  
			"Mega Drain",	
			"Megahorn",  
			"Memento",
			"Metal Claw",	  
			"Metal Sound",	
			"Meteor Mash",
			"Mimic",
			"Mind Reader",	  
			"Minimize",  
			"Mirror Coat",	  
			"Mirror Move",	  
			"Mist",
			"Mist Ball",	
			"Moonlight",	  
			"Morning Sun",
			"Mud Shot",	
			"Mud Sport",
			"Mud-Slap",	
			"Muddy Water",	
			"Nature Power", 
			"Needle Arm",
			"Night Shade",
			"Odor Sleuth",  
			"Outrage",
			"Overheat",
			"Oblivion Wing",
			"Peck",
			"Perish Song",	
			"Petal Dance",
			"Pin Missile",
			"Pluck",
			"Poison Fang",	  
			"Poison Gas",
			"Poison Sting",		
			"Poison Tail",
			"Poisonpowder",	  
			"Pound",
			"Powder Snow",  
			"Protect", 	  
			"Psybeam",	  
			"Psych Up",	  
			"Psychic",
			"Psywave",	
			"Pursuit",	
			"Quick Attack",	  
			"Rage",
			"Rain Dance",
			"Rapid Spin",
			"Razor Leaf",
			"Razor Wind",
			"Recover",
			"Reflect",
			"Refresh",	  
			"Rest",
			"Return",
			"Revenge",
			"Reversal",  
			"Roar",
			"Rock Blast",
			"Rock Slide",
			"Rock Smash",
			"Rock Throw",
			"Rock Tomb",
			"Role Play",
			"Rollout",
			"Safeguard",
			"Sand Tomb",
			"Sand-Attack",
			"Sandstorm",
			"Screech",
			"Secret Power",
			"Seismic Toss",
			"Selfdestruct",
			"Shadow Ball",
			"Shadow Punch",
			"Sheer Cold",
			"Shock Wave",
			"Signal Beam",
			"Silver Wind",
			"Sing",
			"Skill Swap",
			"Skull Bash",
			"Sky Attack",
			"Sky Uppercut",
			"Slack Off",
			"Slam",
			"Slash",
			"Sleep Powder",
			"Sleep Talk",
			"Sludge",
			"Sludge Bomb",
			"Smellingsalt",
			"Smog",
			"Smokescreen",
			"Snatch",
			"Snore",
			"Solarbeam",
			"Sonicboom",
			"Spark",
			"Spike Cannon",	
			"Spikes",
			"Spit Up",
			"Spite",
			"Splash", 
			"Spore",
			"Steel Wing",
			"Stockpile",
			"Stomp",
			"Strength",
			"String Shot",
			"Struggle",
			"Stun Spore",
			"Submission",
			"Substitute",
			"Sunny Day",
			"Superpower",
			"Supersonic",
			"Surf",
			"Swagger",
			"Swallow",
			"Sweet Kiss",
			"Sweet Scent",
			"Swift",
			"Swords Dance",
			"Synthesis",
			"Tackle",
			"Tail Glow",
			"Tail Whip",
			"Take Down",
			"Taunt",
			"Teeter Dance",
			"Teleport",
			"Thief",
			"Thrash",
			"Thunder",	
			"Thunder Wave",
			"Thunderbolt",
			"Thunderpunch",
			"Thundershock",
			"Tickle",
			"Torment",  
			"Toxic",
			"Tri Attack",
			"Trick",
			"Twister",	  
			"Uproar",
			"Vicegrip",
			"Vital Throw",
			"Water Gun",
			"Water Pulse",
			"Water Sport",
			"Water Spout",
			"Waterfall",
			"Weather Ball",
			"Whirlpool",
			"Whirlwind",
			"Will-O-Wisp",
			"Wing Attack",
			"Wish",
			"Wrap",
			"Yawn",
			"Zap Cannon",
		]
	},
	{
		categ: "7 letter words",
		list: [
			"Abalone",
			"Abandon",
			"Ability",
			"Acidity",
			"Acrylic",
			"Aerator",
			"Anthill",
			"Aerosol",
			"Alumnus",
			"Android",
			"Anemone",
			"Ascetic",
			"Anthrax",
			"Anagram",
			"Alfalfa",
			"Agendum",
			"Baloney",
			"Burrito",
			"Bifocal",
			"Cheerio",
			"Cardoor",
			"Cassidy",
			"Culvert",
			"Cynical",
			"Equiox",
			"Factoid",
			"Hydrant",
			"Illicit",
			"Militia",
			"Nitrate",
			"Nucleus",
			"Narcism",
		]
	},
	{
		categ: "Elements",
		list: [
			"Astatine",
			"Barium",
			"Berkelium",
			"Beryllium",
			"Bismuth",
			"Bohrium",
			"Boron",
			"Bromine",
			"Cadmium",
			"Calcium",
			"Californium",
			"Carbon",
			"Cerium",
			"Cesium",
			"Chlorine",
			"Chromium",
			"Cobalt",
			"Copernicium",
			"Copper",
			"Curium",
			"Darmstadtium",
			"Dubnium",
			"Dysprosium",
			"Einsteinium",
			"Erbium",
			"Europium",
			"Fermium",
			"Flerovium",
			"Fluorine",
			"Francium",
			"Gadolinium",
			"Gallium",
			"Germanium",
			"Gold",
			"Hafnium",
			"Hassium",
			"Helium",
			"Holmium",
			"Hydrogen",
			"Indium",
			"Iodine",
			"Iridium",
			"Iron",
			"Krypton",
			"Lanthanum",
			"Lawrencium",
			"Lead",
			"Lithium",
			"Livermorium",
			"Lutetium",
			"Magnesium",
			"Manganese",
			"Meitnerium",
			"Mendelevium",
			"Mercury",
			"Molybdenum",
			"Neodymium",
			"Neon",
			"Neptunium",
			"Nickel",
			"Niobium",
			"Nitrogen",
			"Nobelium",
			"Osmium",
			"Oxygen",
			"Palladium",
			"Phosphorus",
			"Platinum",
			"Plutonium",
			"Polonium",
			"Potassium",
			"Praseodymium",
			"Promethium",
			"Protactinium",
			"Radium",
			"Radon",
			"Rhenium",
			"Rhodium",
			"Roentgenium",
			"Rubidium",
			"Ruthenium",
			"Rutherfordium",
			"Samarium",
			"Scandium",
			"Seaborgium",
			"Selenium",
			"Silicon",
			"Silver",
			"Sodium",
			"Strontium",
			"Sulfur",
			"Tantalum",
			"Technetium",
			"Tellurium",
			"Terbium",
			"Thallium",
			"Thorium",
			"Thulium",
			"Tin",
			"Titanium",
			"Tungsten",
			"Ununoctium",
			"Ununpentium",
			"Ununseptium",
			"Ununtrium",
			"Uranium",
			"Vanadium",
			"Xenon",
			"Ytterbium",
			"Yttrium",
			"Zinc",
			"Zirconium",
			"Actinium",
			"Aluminum",
			"Americium",
			"Antimony",
			"Argon",
			"Arsenic",
		]
	},
	{
		categ: "Pokemon",
		list: [
			"Abomasnow",
			"Abra",
			"Absol",
			"Aerodactyl",
			"Aggron",
			"Aipom",
			 "Alakazam",
			 "Altaria",
			"Ambipom",
			"Ampharos",
			"Anorith",
			"Arbok",
			"Arcanine",
			"Arceus",
			"Ariados",
			"Armaldo",
			"Aron",
			"Articuno",
			"Azelf",
			"Azumarill",
			"Azurill",
			"Bagon",
			"Baltoy",
			"Banette",
			"Barboach",
			"Bastiodon",
			"Bayleef",
			"Beautifly",
			"Beedrill",
			"Beldum",
			"Bellossom",
			"Bellsprout",
			"Bibarel",
			"Bidoof",
			"Blastoise",
			"Blaziken",
			"Blissey",
			"Bonsly",
			"Breloom",
			"Bronzong",
			"Bronzor",
			"Budew",
			"Buizel",
			"Bulbasaur",
			"Buneary",
			"Burmy",
			"Butterfree",
			"Cacnea",
			"Cacturne",
			"Camerupt",
			"Carnivine",
			"Carvanha",
			"Cascoon",
			"Castform",
			"Caterpie",
			"Celebi",
			"Chansey",
			"Charizard",
			"Charmander",
			"Charmeleon",
			"Chatot",
			"Cherrim",
			"Cherubi",
			"Chikorita",
			"Chimchar",
			"Chimecho",
			"Chinchou",
			"Chingling",
			"Clamperl",
			"Claydol",
			"Clefable",
			"Clefairy",
			"Cleffa",
			"Cloyster",
			"Combee",
			"Combusken",
			"Corphish",
			"Corsola",
			"Cradily",
			"Cranidos",
			"Crawdaunt",
			"Cresselia",
			"Croagunk",
			"Crobat",
			"Croconaw",
			"Cubone",
			"Cyndaquil",
			"Darkrai",
			"Delcatty",
			"Delibird",
			"Deoxys",
			"Dewgong",
			"Dialga",
			"Diglett",
			"Ditto",
			"Dodrio",
			"Doduo",
			"Donphan",
			"Dragonair",
			"Dragonite",
			"Drapion",
			"Dratini",
			"Drifblim",
			"Drifloon",
			"Drowzee",
			"Dugtrio",
			"Dunsparce",
			"Dusclops",
			"Dusknoir",
			"Duskull",
			"Dustox",
			"Eevee",
			"Ekans",
			"Electabuzz",
			"Electivire",
			"Electrike",
			"Electrode",
			"Elekid",
			"Empoleon",
			"Entei",
			"Espeon",
			"Exeggcute",
			"Exeggutor",
			"Exploud",
			"Farfetch'd",
			"Fearow",
			"Feebas",
			"Feraligatr",
			"Finneon",
			"Flaaffy",
			"Flareon",
			"Floatzel",
			"Flygon",
			"Forretress",
			"Froslass",
			"Furret",
			"Gabite",
			"Gallade",
			"Garchomp",
			"Gardevoir",
			"Gastly",
			"Gastrodon",
			"Gengar",
			"Geodude",
			"Gible",
			"Girafarig",
			"Giratina",
			"Glaceon",
			"Glalie",
			"Glameow",
			"Gligar",
			"Gliscor",
			"Gloom",
			"Golbat",
			"Goldeen",
			"Golduck",
			"Golem",
			"Gorebyss",
			"Granbull",
			"Graveler",
			"Grimer",
			"Grotle",
			"Groudon",
			"Grovyle",
			"Growlithe",
			"Grumpig",
			"Gulpin",
			"Gyarados",
			"Happiny",
			"Hariyama",
			"Haunter",
			"Heatran",
			"Heracross",
			"Hippopotas",
			"Hippowdon",
			"Hitmonchan",
			"Hitmonlee",
			"Hitmontop|",
			"Honchkrow",
			"Ho-Oh",
			"Hoothoot",
			"Hoppip",
			"Horsea",
			"Houndoom",
			"Houndour",
			"Huntail",
			"Hypno",
			"Igglybuff",
			"Illumise",
			"Infernape",
			"Ivysaur",
			"Jigglypuff",
			"Jirachi",
			"Jolteon",
			"Jumpluff",
			"Jynx",
			"Kabuto",
			"Kabutops",
			"Kadabra",
			"Kakuna",
			"Kangaskhan",
			"Kecleon",
			"Kingdra",
			"Kingler",
			"Kirlia",
			"Koffing",
			"Kricketot",
			"Kricketune",
			"Kyogre",
			"Lairon",
			"Lanturn",
			"Lapras",
			"Larvitar",
			"Latias",
			"Latios",
			 "Leafeon",
			"Ledian",
			 "Ledyba",
			 "Lickilicky",
			 "Lickitung",
			 "Lileep",
			 "Linoone",
			 "Lombre",
			 "Lopunny",
			 "Lotad",
			 "Loudred",
			 "Lucario",
			 "Ludicolo",
			 "Lugia",
			 "Lumineon",
			 "Lunatone",
			 "Luvdisc",
			 "Luxio",
			 "Luxray",
			"Machamp",
			"Machoke",
			"Machop ",
			"Magby",
			 "Magcargo",
			 "Magikarp",
			 "Magmar",
			 "Magmortar",
			 "Magnemite",
			 "Magneton",
			 "Magnezone",
			 "Makuhita",
			 "Mamoswine",
			 "Manaphy",
			 "Manectric",
			 "Mankey",
			 "Mantine",
			 "Mantyke",
			 "Mareep",
			 "Marill",
			 "Marowak",
			 "Marshtomp",
			 "Masquerain",
			 "Mawile",
			 "Medicham",
			 "Meditite",
			 "Meganium",
			 "Meowth",
			 "Mesprit",
			 "Metagross",
			 "Metang",
			 "Metapod",
			 "Mew",
			 "Mewtwo",
			 "Mightyena",
			 "Milotic",
			 "Miltank",
			 "Mime Jr.",
			 "Minun",
			 "Misdreavus",
			 "Mismagius",
			 "Moltres",
			 "Monferno",
			 "Mothim",
			 "Mr. Mime",
			 "Mudkip",
			 "Muk",
			 "Munchlax",
			 "Murkrow",
			 "Natu",
			 "Nidoking",
			 "Nidoqueen",
			 "Nidoran",
			 "Nidorina",
			 "Nidorino",
			 "Nincada",
			 "Ninetales",
			 "Ninjask",
			 "Noctowl",
			 "Nosepass",
			 "Numel",
			 "Nuzleaf",
			 "Octillery",
			 "Oddish",
			 "Omanyte",
			 "Omastar",
			 "Onix",
			 "Pachirisu",
			 "Palkia",
			 "Paras",
			 "Parasect",
			 "Pelipper",
			 "Persian",
			 "Phanpy",
			 "Phione",
			 "Pichu",
			 "Pidgeot",
			 "Pidgeotto",
			 "Pidgey",
			 "Piloswine",
			 "Pineco",
			 "Pinsir",
			 "Piplup",
			 "Plusle",
			 "Politoed",
			 "Poliwag",
			 "Poliwhirl",
			 "Poliwrath",
			 "Ponyta",
			 "Poochyena",
			 "Porygon",
			 "Porygon2",
			 "Porygon-Z",
			 "Primeape",
			 "Prinplup",
			 "Probopass",
			 "Psyduck",
			 "Pupitar",
			 "Purugly",
			 "Quagsire",
			 "Quilava",
			 "Qwilfish",
			 "Raichu",
			 "Raikou",
			 "Ralts",
			 "Rampardos",
			 "Rapidash",
			 "Raticate",
			 "Rattata",
			 "Rayquaza",
			 "Regice",
			 "Regigigas",
			 "Regirock",
			 "Registeel",
			 "Relicanth",
			 "Remoraid",
			 "Rhydon",
			 "Rhyhorn",
			 "Rhyperior",
			 "Riolu",
			 "Roselia",
			 "Roserade",
			 "Rotom",
			 "Sableye",
			 "Salamence",
			 "Sandshrew",
			 "Sandslash",
			 "Sceptile",
			 "Scyther",
			 "Seadra",
			 "Sealeo",
			 "Seedot",
			 "Seel",
			 "Sentret",
			 "Seviper",
			 "Sharpedo",
			 "Shaymin",
			 "Shedinja",
			 "Shelgon",
			 "Shellder",
			 "Shellos",
			 "Shieldon",
			 "Shiftry",
			 "Shroomish",
			 "Shuckle",
			 "Shuppet",
			 "Silcoon",
			 "Skarmory",
			 "Skiploom",
			 "Skitty",
			 "Skorupi",
			 "Skuntank",
			 "Slaking",
			 "Slakoth",
			 "Slowbro",
			 "Slowking",
			 "Slowpoke",
			 "Slugma",
			 "Smeargle",
			 "Smoochum",
			 "Sneasel",
			 "Snorlax",
			"Snorunt",
			"Snover",
			"Snubbull",
			"Solrock",
			"Spearow",
			"Spheal",
			"Spinarak",
			"Spinda",
			"Spiritomb",
			"Spoink",
			"Squirtle",
			"Stantler",
			"Staraptor",
			"Staravia",
			"Starly",
			"Starmie",
			"Staryu",
			"Steelix",
			"Stunky",
			"Sudowoodo",
			"Suicune",
			"Sunflora",
			"Sunkern",
			"Surskit",
			"Swablu",
			"Swalot",
			"Swampert",
			"Swellow",
			"Swinub",
			"Taillow",
			"Tangela",
			"Tangrowth",
			"Tauros",
			"Teddiursa",
			"Tentacool",
			"Tentacruel",
			"Togekiss",
			"Togepi",
			"Togetic",
			"Torchic",
			"Torkoal",
			"Torterra",
			"Totodile",
			"Toxicroak",
			"Trapinch",
			"Treecko",
			"Tropius",
			"Turtwig",
			"Typhlosion",
			"Tyranitar",
			"Tyrogue",
			"Umbreon",
			"Unown",
			"Ursaring",
			"Uxie",
			"Vaporeon",
			"Venomoth",
			"Venonat",
			"Venusaur",
			"Vespiquen",
			"Vibrava",
			"Victreebel",
			"Vigoroth",
			"Vileplume",
			"Volbeat",
			"Voltorb",
			"Vulpix",
			"Wailmer",
			"Wailord",
			"Walrein",
			"Wartortle",
			"Weavile",
			"Weedle",
			"Weepinbell",
			"Weezing",
			"Whiscash",
			"Whismur",
			"Wigglytuff",
			"Wingull",
			"Wobbuffet",
			"Wooper",
			"Wormadam",
			"Wurmple",
			"Wynaut",
			"Xatu",
			"Yanma",
			"Yanmega",
			"Zangoose",
			"Zapdos",
			"Zigzagoon",
			"Zubat",
		]
	},
	{
		categ: "Abilities",
		list: [
			"Adaptability",
			"Technician",
			"Aftermath",
			"Air Lock",
			"Cloud Nine",
			"Anger Point",
			"Anticipation",
			"Forewarn",
			"Arena Trap",
			"Magnet Pull",
			"Shadow Tag",
			"Bad Dreams",
			"Battle Armor",
			"Shell Armor",
			"Blaze",
			"Overgrow",
			"Swarm",
			"Torrent",
			"Cacophony",
			"Soundproof",
			"Chlorophyll",
			"Swift Swim",
			"Clear Body",
			"Hyper Cutter",
			"White Smoke",
			"Color Change",
			"Forecast",
			"Compound Eyes",
			"Keen Eye",
			"Cute Charm",
			"Effect Spore",
			"Flame Body",
			"Poison Point",
			"Static",
			"Damp",
			"Download",
			"Drizzle",
			"Drought",
			"Sand Stream",
			"Drought",
			"Dry Skin",
			"Rain Dish",
			"Early Bird",
			"Vital Spirit",
			"Effect Spore",
			"Cute Charm",
			"Flame Body",
			"Poison Point",
			"Static",
			"Flash Fire",
			"Volt Absorb",
			"Water Absorb",
			"Flower Gift",
			"Gluttony",
			"Guts",
			"Huge Power",
			"Hustle",
			"Ice Body",
			"Rain Dish",
			"Illuminate",
			"Stench",
			"Inner Focus",
			"Insomnia",
			"Limber",
			"Magma Armor",
			"Oblivious",
			"Own Tempo",
			"Water Veil",
			"Inner Focus",
			"Immunity",
			"Insomnia",
			"Intimidate",
			"Iron Fist",
			"Keen Eye",
			"Levitate",
			"Thick Fat",
			"Wonder Guard",
			"Lightningrod",
			"Limber",
			"Liquid Ooze",
			"Marvel Scale",
			"Minus",
			"Plus",
			"Mold Breaker",
			"Teravolt",
			"Turboblaze",
			"Moody",
			"Natural Cure",
			"Pickup",
			"Poison Point",
			"Pressure",
			"Pure Power",
			"Adaptability",
			"Thick Fat",
			"Levitate",
			"Wonder Guard",
			"Torrent",
			"Blaze",
			"Trace",
			"Truant",
			"White Smoke",
			"Water Viel",
			"Ice Body",
			"Pixilate",
		]
	}
];